dist: trusty
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost 
sudo: false
language: node_js
node_js:
  - stable
script: 
  - npm test
# after_success:
#  - npm run report-coverage